### ISSUE TITLE
Seems like old fashioned vulnerability

### ISSUE THREAD

**Issue by MChaban47** [php/doc-it#41]
https://github.com/php/doc-it/blob/bb0149be4579d5bbc3c3ade14b1161317394453a/reference/pcre/pattern.modifiers.xml#L114

**Comment by DavidePastore** [comment]
Hi @MChaban47. Could you please elaborate a bit more?

**Comment by MChaban47** [comment]
@DavidePastore, look at line 120
In PHP prior 7.0, 'e' modifier will evaluate result of preg_replace as PHP code.
If this '.xml' file will be handled by PHP interpreter on server (if set so) - it becomes a backdoor with remote shell possibility or any PHP function execution on remote server.
I mean, I know that this is an example, but it will actually be executed on server with documentation where all files go through the PHP interpreter.
You can find out more here: http://www.madirish.net/402

**Comment by DavidePastore** [comment]
@MChaban47, thank you for elaborating more. This file should be updated to the latest available content of the corresponding [doc-en](https://github.com/php/doc-en) language [file](https://github.com/php/doc-en/blob/master/reference/pcre/pattern.modifiers.xml) in order to get rid of this issue.

**Comment by DavidePastore** [comment]
To be honest I'm not even sure that the code snippets that are in the example sections are executed by a PHP interpreter.

**Comment by Girgias** [comment]
> To be honest I'm not even sure that the code snippets that are in the example sections are executed by a PHP interpreter.

They are not :)
